name: Build release Docker Images

on:
  push:
    branches: [main] # $default-branch

jobs:
  failed-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the CI build on main
        run: exit 1
