name: Succeed

on:
  pull_request:

jobs:
  succeeded-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Succeed the CI build on main
        run: exit 0
      - uses: ./.github/actions/notify-failure
        if: ${{ failure() }}
        with: 
          sendgrid_api_key: ${{ secrets.EMAIL_PASSWORD }}
          recipients: ${{ secrets.EMAIL_DESTINATION }}
